#definimos los contenedores(servicios)
services:
  #contenedor de mysql(BD)
  mysql-db:
    env_file:
      #ruta de .env de BD
      - ./db/.env

    #docker descarga la version de mysql especificada
    image: mysql:8.0
    container_name: mysql-gestion

    #indica que si el pc se reinicia o el proceso mysql falla,docker lo levanta automaticamente
    restart: always

    #variables de entorno
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Te recomiendo poner una aunque sea simple
      MYSQL_DATABASE: "gestion_tecnica2"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: 
    
    #mapea el puerto local(izq) al del contenedor(der)
    ports:
      - "3306:3306"

    #persistir datos(volumenes)
    volumes:
      - db_data:/var/lib/mysql 

  servicio-academico:
    #se busca un Dockerfile en la carpeta especificada y se "cocina" el codigo
    build: 
      context: .
      dockerfile: ./servicio-academico/Dockerfile
    container_name: servicio-academico
  
    #mapea puerto local 3307 al mismo del contenedor
    ports:
      - "3307:3307"

    environment: 
      # Usamos las credenciales definidas arriba
      DATABASE_URL: "mysql://root@mysql-db:3306/gestion_tecnica2"

    #el servicio no arranca hasta que el servicio especificado(mysql) este prendido
    depends_on:
      - mysql-db

volumes:
  db_data: